### ISSUE TITLE
Expose or link to awesome-ipfs in WebUI and/or Desktop

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-shipyard/ipfs-webui#1406]
Currently, the explore tab just shows always the same stuff, while we already have a very nice website in IPFS which shows much more stuff you can do with IPFS. How about showing it in the explore tab?

https://awesome.ipfs.io/

**Comment by jessicaschilling** [comment]
Hi @rubenkelevra - thanks for the feedback! Regardless of whether we might actually want to *replace* the IPLD Explorer content with material from awesome-ipfs, you bring up a really good point about the value of providing links to (or embedded content from) awesome-ipfs within WebUI and/or Desktop. Let's use this issue to discuss where and how we might want to do that?

You might be interested to know about issue https://github.com/ipfs-shipyard/ipld-explorer/issues/55 -- adding explanatory info/context to IPLD Explorer as a whole in order to make it more useful and interesting.

Contributions on both of these issues more than welcome! Thanks.

**Comment by jessicaschilling** [comment]
Let's actually close this issue and roll its content into https://github.com/ipfs-shipyard/ipfs-webui/issues/1463 -- enhancement of the existing welcome screen. Thanks!
