### ISSUE TITLE
Add CLI "tutor mode" to Web UI/Desktop

### ISSUE THREAD

**Issue by lanzafame** [ipfs-shipyard/ipfs-webui#1421]
## This issue has a bounty!
Successfully closing this issue by making a PR of production-ready code can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## How to claim this bounty
Want to work on this bounty project? Please leave a comment on this issue, and we'll be back in touch ASAP to discuss specifics. **Note that because this project requires changes to the existing UI, we'll want to work closely on making sure the solution integrates well with current patterns.**

## The need in brief
Meet the needs expressed in the original proposal below by adding some form of "CLI tutor mode" to IPFS Web UI (which, in turn, will be included in IPFS Desktop, since they share this portion of the codebase). The solution should ...

- Enable the user to generate copy/paste-able CLI snippets for the actions available in Web UI, with an aim to making it easier for newer IPFS users to self-learn the CLI
- Be readily available for such users, but not so unavoidable that users who don't want to take advantage of the feature can't ignore it

### Original proposal from @lanzafame 
I was just creating a VM on GCP and they have a button at the end that takes a UI hand-craft VM creation and turns it into either a curl request or a gcloud cli command and thought it would be cool to have something similar for the webui so if people wanted to know how to pin something like they are in the webui on the cli, they could get the command and the arguments that they had already input. Sort of a self-teaching moment for the curious
<img width="842" alt="Screen Shot 2020-03-27 at 13 37 02" src="https://user-images.githubusercontent.com/5924712/77866126-1490de80-7275-11ea-85f0-2181f47825dd.png">

**Comment by jessicaschilling** [comment]
@lanzafame This is such a cool idea 😊 ... and also sort of a big chunk to bite off. Do you think it's something that would be appropriate to put out for a bounty? Otherwise I fear it might languish just given current resourcing. Any other thoughts from your end?

**Comment by lanzafame** [comment]
@jessicaschilling I think that is a great idea.

**Comment by jay-dee7** [comment]
hey @lanzafame, can i please start working on this over the weekend?

**Comment by lanzafame** [comment]
@jay-dee7 sure thing

**Comment by jessicaschilling** [comment]
@jay-dee7 I’ll assign you, but as noted above, please check in first with sketches/descriptions of where and how this will appear in the interface before getting too deep in the work. There’s a pretty substantial impact on the UI, so we want to be sure this is implemented in a way that supports but doesn’t distract the reader. (This is also one of the conditions for bounty payout.) Thank you!

**Comment by jessicaschilling** [comment]
Screenshots and any descriptions to explain them would be great. We don’t have existing designs, unfortunately, but please borrow from any existing metaphors/patterns already in the app that are analogous. Thanks!

**Comment by jay-dee7** [comment]
@jessicaschilling i was wondering about how to approach this. Do we really need to pop up a modal to display the content? or simply by clicking, you copy the command to the clipboard?

Like check this example, if we want to overwrite the settings, we can either do this,

**Comment by jay-dee7** [comment]
@jessicaschilling i was wondering about how to approach this. Do we really need to pop up a modal to display the content? or simply by clicking, you copy the command to the clipboard?

Like check this example, if we want to overwrite the settings, we can either click on a button, to open a modal, we display whats going to happen and then give the user an option to copy the equivalent command
<img width="1680" alt="Screenshot 2020-05-02 at 2 28 48 PM" src="https://user-images.githubusercontent.com/10788442/80859829-4258b100-8c81-11ea-82c0-90b6808e453a.png">
 or we instead of opening a modal, we just copy the command to his clipboard?
ps: dont mind the wrong texting in the screenshot, i'll fix it later on and post more of them

**Comment by jessicaschilling** [comment]
@jay-dee7 That’s a good question. One thing to consider is how *you* might like to learn a new CLI tool, as well as how existing ways of learning new CLI tools present the info. 

Everyone’s needs and wishes are different, but I might suggest that we want to present the info in a modal (or some other form of fallout, but a modal seems most obvious) for a few reasons:
- Most IPFS commands are a lot shorter than that big block of json, so we aren’t as likely to present the user with a big, maybe overwhelming modal like the original illustration
- The user might just want to _see_ the equivalent command but not actually use it in the terminal (for example, there may be someday when the user is using webUI on a phone and doesn’t have a terminal available)
- The user might still paste into a terminal, but their terminal makes it hard to read (and understand) long commands

Suggestion: if you want to research this deeper, look around at other similar situations and tools out in the wild and see how they handle similar scenarios. It doesn’t have to be code snippets, just any other examples of “discover another way of doing a thing” you can find. People do best learning new ways to do things when they’re presented with familiar patterns. 

Great work so far and thank you for checking in!

**Comment by jay-dee7** [comment]
@jessicaschilling i understand, a modal makes a lot more sense than just plain copy-command approach, there's a lot we can do to help under understand the CLI approach much better. i tried digging in the code a bit and understand it. I'll keep you guys posted with the development :)

**Comment by jay-dee7** [comment]
hey @jessicaschilling , i'm so so sorry for delaying this one. Been caught up with tons of work at office lately. I spent few hours this weekend trying to understand how `redux-bundler-react` works in the webapp and also i've tried to move a bit forward.
I've made small changes to the UI (trying to not drift away from the existing development patterns), nothing much bold tho. Please take a look at this and let me know if it's okay to follow this path

![image](https://user-images.githubusercontent.com/10788442/85228026-90c33a00-b3fe-11ea-9c5c-b1d459e11d55.png)

![image](https://user-images.githubusercontent.com/10788442/85228330-81dd8700-b400-11ea-922e-73282ca5854f.png)


Since settings page in particular has so much space, it seems possible to add a BUTTON but there are other places where we dont have enough space like `Add Connection` in peers page

![image](https://user-images.githubusercontent.com/10788442/85228397-e00a6a00-b400-11ea-92f0-cb7bb44740b6.png)

So maybe i should add a smaller outline button? or a tooltip? since having different kinds of buttons on different pages might confuse the user. A tooltip seems like a good fit here. please let me know you opinion on this.

**Comment by jessicaschilling** [comment]
Thank you for the updates! I'm going to make two comments -- this first one deals with where the on/off switch for this should live, and the other will deal with the interaction itself 😊 

As far as where we should put the option to turn tutor mode on/off, let's include it in the preferences screen as such. Feel free to reword if you find the text confusing. It would also be good to include an image of the icon itself after the text "'copy code' icons" in the messaging itself -- pardon me for not doing so in the screenshot! 

![image](https://user-images.githubusercontent.com/1507828/85450940-9338a780-b556-11ea-9323-4506798e97ef.png)

The second comment may take a bit to get down on paper, so please bear with me.

**Comment by jessicaschilling** [comment]
(comment 2/2) - this one deals with how the option to copy CLI commands should be implemented visually within the UI.

**First, we need to consider all the places where this option might exist.** I quickly round up the following, but please have a look to see if there are others not on this list:
- Files screen > "Add" button > "New folder" (results in a modal popping up)
- Files screen > "Add" button > "Add from IPFS" (results in a modal)
- Peers screen > "Add connection" button (results in a modal)
- Settings screen > "IPFS Config" section (as an aside, the CLI resulting from this should be to open the config file in an editor)
- Home screen (the one you get to when you click the up/down icon in the top right of every window) > set custom API field > "Submit" button
- Files screen > "three dots" action menu > "Delete" (results in a confirmation modal)
- Files screen > "three dots" action menu > "Rename" (results in a modal)
- Files screen > "three dots" action menu > "Download" (results in native OS save-file window)
- Files screen > "three dots" action menu > "Pin" or "Unpin"

**Next, we need to solve for how this will appear in a consistent manner across all those items above.** One approach to this would be to include a "copy code" icon *next to* the button/menu option that would ordinarily *start* the process of performing the action in the GUI -- i.e. rather than putting the "copy code" icon in the modal that opens when you click on "Add from IPFS", we'd put the icon next to the "Add from IPFS" option. Examples of how that could potentially look (icon itself can be found [here](https://gateway.ipfs.io/ipfs/QmSLoi5nofYtVkvJDsPxfgrt1XeBVoMcEbZx3mFMKdXdts)):
![image](https://user-images.githubusercontent.com/1507828/85457929-cb8fb400-b55d-11ea-9846-b6779a113146.png)
![image](https://user-images.githubusercontent.com/1507828/85457940-d21e2b80-b55d-11ea-82c4-23582a901989.png)
![image](https://user-images.githubusercontent.com/1507828/85457960-d77b7600-b55d-11ea-95f5-177d5bfd167a.png)
![image](https://user-images.githubusercontent.com/1507828/85457981-dd715700-b55d-11ea-98bc-f19db14e4cfe.png)
Note that if we took this route of visual implementation, we'd have to make sure that when the icon appears in a menu, the user can clearly discern between clicking on the menu item and clicking on the icon.

**Finally, we'd need to solve for what happens after the user clicks on the icon. The modal you reference [here](https://user-images.githubusercontent.com/10788442/85228330-81dd8700-b400-11ea-922e-73282ca5854f.png) is a great start, though I might remove the megaphone icon (it's not needed in this context) and tweak the explanatory text a bit: maybe "Replace any placeholder text and copy this command into your terminal to use the IPFS command-line interface." The button could just say "Copy" -- "clipboard" is pretty implicit here.

Please don't consider any of the above set in stone -- happy to iterate on this if you see room for improvement!

**Comment by jay-dee7** [comment]
hey @jessicaschilling, i think it's a great idea to include the option to enable cli tutor mode inside the preferences page.
Including an icon next to the buttons also looks great (icon itself is beautiful). I'll try to find all the places that can can have an equivalent CLI command.

As for the modal, i was really trying to reuse the components which were already present in the code, before making any submission, i'll make sure to remove anything that doesn't add up.
Thanks a ton for spending so much time and making everything clear :)

**Comment by jay-dee7** [comment]
hey @jessicaschilling i was able to make some progress this weekend. Here's what i've done
1. changed the text as you requested
2. added the new copy icon
3. added the cli tutor component in the files pages
4. made the existing dropdown options distinguishable from the copy icon

I think i'm very close the end of the task but i did run into some issues while trying to retrieve the individual file names and passing them along to generate their cli equivalent commands (which is why we see [object object] in the modal) but i'll figure it out soon enough. Here are a bunch of screenshots 😄 

![ipfs-webui-u1](https://user-images.githubusercontent.com/10788442/87879877-e6ddca00-ca0a-11ea-91c8-c0b3eab85b83.png)
![ipfs-webui-u2](https://user-images.githubusercontent.com/10788442/87879836-bc8c0c80-ca0a-11ea-8f4a-98d51982fc4b.png)
![ipfs-webui-u3](https://user-images.githubusercontent.com/10788442/87879839-bdbd3980-ca0a-11ea-850b-c4a92130cb68.png)

**Comment by jessicaschilling** [comment]
@jay-dee7 Thanks for the update! Let me know when you're ready for a more thorough PR review ... I have a few tiny visual tweaks in mind based on your screenshots (just to bring them a little more in line with the mockups) but we should just go through everything all at once when you're ready. This looks great so far!
