### ISSUE TITLE
Untranslatable string in help menu

### ISSUE THREAD

**Issue by Luflosi** [ipfs-shipyard/ipfs-webui#1439]
**Describe the bug**
The help menu that appears when clicking the little question mark in the top right corner has "Back" and "Next" buttons that appear to not be translatable. I couldn't find the text for the two buttons in transifex and the German translation for the Web UI is complete. I also couldn't find the two strings when using the GitHub search function to search in this project or during a quick look in the source code. Maybe they are added by some framework.
The "CONNECTION" and "NOTES" headers in the peer table, "Explore" on the left and a few more things seem to also not be translatable but I haven't really investigated these yet.

**To Reproduce**
1. Change the language to "Deutsch" (German) in the settings
2. Click the little question mark in the top right
3. See "Next (1/4)"

**Expected behavior**
These two words should be translatable.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/15217907/79462533-e5f66000-7ff7-11ea-869c-6b55ec3c820d.png)

**Comment by jessicaschilling** [comment]
@lidel Do you have time to take a look?

**Comment by lidel** [comment]
Yup, did a quick pass and identified the source of the problem:

ipfs-webui uses `react-joyride` for those help tour popups, and we do not pass translations to that library.

Potential fix would be to 

1. add `tour.back,close,last,next,skip` keys to every file with `tour` section  in `public/locales/en/*.json`
   - Caveat: Transifex will reuse translations for the same key, but we need to define the same key in every file due to the way webui is designed
1. add `locale` [property](https://docs.react-joyride.com/props) everywhere `ReactJoyride` is used, i imagine more-or-less something like:
   ```jsx
   import { Trans } from 'react-i18next'

   // load translation via i18next:
   const localeMap = {
     back: <Trans i18nKey='tour.back'>, 
     close: <Trans i18nKey='tour.close'>, 
     last: <Trans i18nKey='tour.last'>, 
     next: <Trans i18nKey='tour.next'>, 
     skip: <Trans i18nKey='tour.skip'>, 
   }
   ```
 
   ```jsx
       // pass translation to react-joyride:
       <ReactJoyride
         locale={localeMap}
         // ...
   ```

Hope this helps!

----
 
@jessicaschilling  perhaps fixing this could be a good warmup task for @rafaelramalho19 to learn how our i18n setup works?

**Comment by jessicaschilling** [comment]
@lidel - good call. @rafaelramalho19, I'm going to assign this one to you -- can you please take a crack at it? Thanks!
