### ISSUE TITLE
IPLD explorer category not available in transifex

### ISSUE THREAD

**Issue by Luflosi** [ipfs-shipyard/ipfs-webui#1477]
**Describe the bug**
I noticed, that https://github.com/ipfs-shipyard/ipfs-webui/tree/master/public/locales/de contains six files (`explore.json`, `files.json`, `peers.json`, `settings.json`, `status.json` and `welcome.json`) but `explore-json` is missing from transifex, at least for the german translation:
![screenshot](https://user-images.githubusercontent.com/15217907/80493594-e7b01400-8965-11ea-8099-6b132c24d963.png)
When I search for any string in `explore.json` I also can't find it on transifex.
Am I doing something wrong?

**Comment by bertrandfalguiere** [comment]
Same problem in French: file is missing from Transifex

**Comment by jessicaschilling** [comment]
Thanks, @bertrandfalguiere and @Luflosi, for spotting this! We're all a bit all-hands-on-deck today with the most recent go-ipfs release, but rest assured we'll look ASAP.

**Comment by lidel** [comment]
Thank you for bringing this to our attention: this is a sideffect of current design.

The IPLD Explorer is both a subscreen in ipfs-webui but also a standalone web app at https://explore.ipld.io/ – the repo for https://explore.ipld.io website  is [ipld-explorer
](https://github.com/ipfs-shipyard/ipld-explorer)

Both ipfs-webui and ipld-explorer website depend on shared components from [ipld-explorer-components](https://github.com/ipfs-shipyard/ipld-explorer-components), and that is where translations of IPLD Explorer live. They are exposed on Transifex under  https://www.transifex.com/ipfs/ipld-explorer/ and you can translate strings there.

The problem here is that we did not had bandwidth to bubble up new ipld-explorer-components (with updated translations) to ipfs-webui yet. But don't worry, we will :)

cc @rafaelramalho19 – we should do this before we make next release, if possible.

**Comment by kartezjusz** [comment]
CZYTAJ OPIS ZANIM BĘDZIE ZA PÓŹNO-
porównaj numery z tego opisu z numerami z ogłoszeń
Piotra Piasty Wrocław PIOTR WALDEMAR PIASTA „DIGITAL SYSTEMS” Wrocław al. Poprzeczna 66/6 ul / al Manganowa 27/7 (7/27 na przemiennie) dane z CEIDG NIP-8951647389 kryptokoparki24.pl Telefony: 600465412, 796745805, 574517679, 796051081, 574143177, 576904953, ksywy= Kartezjusz Kowalski, Peter Kowalski, Piotr Kowalski, Piotr Nowak. meile jakich urzywa walt666 kartysim1 kartysim2 mbtpozew  loginy: walt666, WUPE Właściciel stron sprawdz-numerek.pl, czyjnumerek.pl i wszyscy ci na których są opinie na temat jego tematu.
Odradzam jak w celach zleceniobiorców i sprzedawców, chyba ze chce się wzbogacić o stalking internetowy.


Pan gotów jest sam zrujnować osobę, instytucję oraz wykonana prace, nie przestrzegać żadnych zasad etycznych, handlowych  czy zaleceń eksploatacyjnych jako klient a potem nie da wam żyć i wykorzystując KONTAKTY u administratorów stron internetowych (allegro,oferia,youtube) i znajomości w branży IT i mając parę stron internetowych w tym sprawdz-numerek.pl i czyjnumerek.pl na fałszywe pozytywne opinie pisane przez siebie, fałszywe dane oraz zagraniczne serwery będzie uporczywie nękał i szkalował w internecie Was, Wasze firmy, rodziny i dzieci, dzwonił nocami z prywatnego, latał dornem pod domem robiąc zdjęcia, wstawiał przez boty setki negatywnych opinii, kręcił filmy z ukrycia i publikował je w internecie, wstawianie numerów telefonu w anonse erotyczne, rejestrowanie waszych adresów meilowych na portalach zagranicznych śmieciowych, wysyłanie na meila wirusów,linków z wtyczkami aby się dostać do danych z komputerów jak i telefonów, wysyłanie listów,kurierów, sms stosował szantaż i wszelkie krętackie metody by zmęczyć was psychicznie, bo na rozstrzyganie spraw w sadzie lub inny cywilizowany sposób jest za cienki. Gość to materiał i dla prokuratora i dla dziennikarza i psychiatry (ale od tego ostatniego to ma klinikę zony Moniki)


A tak Wygląda, to jego aktualne zdjęcie z lokalnego przewodnika google(należny skopiować link i wkleić do przeglądarki): images.app.goo.gl/xDnHHR3AfKHcDosE7
Poszukuje osób które w ten sam sposób są nękane lub poszkodowane (temat pobierania pieniedzy za rejestracje kart i nie wysylanie towaru) prosze o kontakt: pozew_na_kartezjusza@o2.pl
Pomoc prawna bezpłatna.
