### ISSUE TITLE
Resolve upload memory leaks

### ISSUE THREAD

**Issue by rafaelramalho19** [ipfs-shipyard/ipfs-webui#1488]
Since it's not possible to split a file upload into multiple chunks, the memory usage while uploading files to the browser increases according to the size of the file (e.g. 1GB of file size -> 1GB of RAM used).

Since this limits our users from uploading files that are bigger than the remaining memory through WebUI, this is probably important for most users.

As discussed, a better alternative to HTTP uploads would be to use RPC.

Relevant participants:
@achingbrain 
@hugomrdias 
@gozala

**Comment by Gozala** [comment]
@rafaelramalho19 I believe it is possible to upload without loading it all into memory through [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) of a [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) body.

It is possible by creating a Readable Stream which reads file slices on pull instead of reading the whole file into memory

**Comment by lidel** [comment]
I believe this was fixed in https://github.com/ipfs-shipyard/ipfs-webui/pull/1534
