### ISSUE TITLE
0.7.0 How to UnPin?

### ISSUE THREAD

**Issue by ldeffenb** [ipfs-shipyard/ipfs-webui#1648]
**Describe the bug**
I have 5 pins showing in the Files tab.  When I click on the 5 pins link, it shows me the 5 pins that I know I have.  However, their 3 dots menu on the right shows a "Pin" option, but no "UnPin" option?  If they're pins, why offer Pin and how so I UnPin them?

The same is true of the 3 dots menu on the original 2 UnixFS file roots that I have pinned (which is 2 of the 5 pins).  They also offer only a "Pin" option and no way to "UnPin".

**To Reproduce**
1. Browse to some arbitrary CID (say QmXDVH72tG4VVKzfdnhp1HjLiy9ULyYokoXkw2Nby8LY3S) - It will shows as "[object Object]"
2. Click the ...More menu and select Pin
3. Go back to the Files tab, your Pin count should have increased by one - Click on that
4. You should see the 28 byte pin of the CID above somewhere in your list (it moves around, why?)
5. Click the 3 dots menu on that entry and it still offer "Pin".  How do I Unpin that CID?

**Expected behavior**
One would expect a list of Pins to have an UnPin option, not a Pin option.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IPFS is on Ubuntu
 - Chrome 
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
I upgraded from 0.6.0 to 0.7.0 and the behavior started this way.  0.6.0 allowed me to unpin IIRC.

**Comment by jessicaschilling** [comment]
@lidel and @rafaelramalho19 - this is similar behavior to that addressed in https://github.com/ipfs-shipyard/ipfs-webui/pull/1633. Can you please investigate?

**Comment by lidel** [comment]
I can confirm the bug in go-ipfs v0.7.0 and ipfs-desktop v2.11.1, and that the bug is fixed in `master` thanks to #1633 – nothing to do here, we just need a new release.

---- 

@ldeffenb if you need a workaround for now, here is one:

- When `/pins` list is shown, none of pins is marked as pinned (this bug). However, [there is a confusing option to _Pin_ already existing pin](https://user-images.githubusercontent.com/157609/94280594-e05d5880-ff4d-11ea-9993-f95213e252a6.png). 
- Workaround is to do a redundant pin via context menu, then item will be marked as pinned and you will be able to unpin it via  [_Unpin_ action](https://user-images.githubusercontent.com/157609/94280772-18649b80-ff4e-11ea-8217-8f7efac32348.png).

Note that everything in Files (MFS) is "implicitly pinned" (protected from gc), so you don't need low level pins to keep stuff around. 

Low level command `ipfs pin` is mostly aimed at backend use, and we are planning to remove Pin count and  `/pins` view as part of pinning services integration ([screenshot](https://github.com/ipfs-shipyard/ipfs-webui/pull/1513#pullrequestreview-424868848) / #1615).

**Comment by ldeffenb** [comment]
@lidel My workaround was to drop back to 0.6.0.  The Delete option is also missing from the MFS Files display and I needed to delete one of my 2 17+GB trees.

**Comment by jessicaschilling** [comment]
@ldeffenb -- the issue I believe you're mentioning with missing items in contextual menus has been fixed in https://github.com/ipfs-shipyard/ipfs-webui/issues/1631 (again, in `master` but awaiting imminent new release). Note that they should still be available in the bottom drawer menu (see illustration in https://github.com/ipfs-shipyard/ipfs-webui/issues/1631); if you're experiencing something different, though, would appreciate any details.

**Comment by ldeffenb** [comment]
@jessicaschilling Confirmed.  The missing menu items are those mentioned in #1631 Thank you.
