### ISSUE TITLE
Report a bug on IPFS Desktop redirects here

### ISSUE THREAD

**Issue by NukeManDan** [ipfs-shipyard/ipfs-webui#1664]
**Describe the bug**
Report a bug on IPFS Desktop redirects here: https://github.com/ipfs-shipyard/ipfs-webui/issues/

It should redirect to https://github.com/ipfs-shipyard/ipfs-desktop/issues

**To Reproduce**

Bottom left corner of IPFS desktop:

![image](https://user-images.githubusercontent.com/35669742/95280429-349bee80-0812-11eb-9608-447eb22cac98.png)

**Comment by jessicaschilling** [comment]
Hi @NukeManDan - this is actually intentional, as in the majority of instances issues found in Desktop actually have their sources in Web UI. As Desktop is an Electron standalone version of Web UI (with the addition of functionality in the menubar/system tray), the bulk of the potential "issue surface" is within Web UI itself. 

Will close this issue with that in mind, but appreciate you raising it!
