### ISSUE TITLE
Can't add a new quic connection via the Desktop UI 

### ISSUE THREAD

**Issue by lanzafame** [ipfs-shipyard/ipfs-webui#1674]
**To Reproduce**
1. Go to Peers
2. Click on '+Add connection'
3. Enter peer address that uses quic transport
4. Pop up doesn't allow the value to be entered

**Expected behavior**
It is a valid address and should be accepted

**Screenshots**
<img width="482" alt="Screen Shot 2020-10-20 at 11 14 39" src="https://user-images.githubusercontent.com/5924712/96528347-d6691400-12c5-11eb-9ee2-ca3ebfea71cd.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 
 - Version:  UI 2.11.4

**Additional context**

**Comment by jessicaschilling** [comment]
NB: this is a duplicate of https://github.com/ipfs-shipyard/ipfs-webui/issues/1533 -- let's close one or the other after we triage.

**Comment by zhqu1148980644** [comment]
What's the prograss

**Comment by lidel** [comment]
@zhqu1148980644  This will be fixed by https://github.com/ipfs-shipyard/ipfs-webui/pull/1689

Until that ships in a new release, as a workaround you can enter only the suffix  `/p2p/{peerid}` 
It will be a bit slower  (node will find quic addr over DHT, which may take time), but should work in most cases.
