### ISSUE TITLE
Improve the data flow

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-webui#227]
At the moment there are major issues with the way api requests are made and timeouts are being set and requests not being cleaned up. As a first step to counter these issues we need to use some data flow architecture. I'm at the moment researching Redux and will start on an implementation in the next days.

This superseeds #199

**Comment by aeschylus** [comment]
I would also recommend looking into Rx as an option. I just finished this [excellent series](https://egghead.io/series/cycle-js-fundamentals) by [André Staltz](http://staltz.com/), who wrote the [_Introduction to Reactive Programming You've been Missing_](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754), and authored [CycleJS](https://egghead.io/series/cycle-js-fundamentals) as well as this mind-opening _["Unidirectional Interface Architectures"](http://staltz.com/unidirectional-user-interface-architectures.html)_ article. [This segment](https://egghead.io/lessons/rxjs-an-interactive-counter-in-cycle-js) of the aforementioned series shows an entirely flow-based representation of the application state based on observables (just a counter example, but if you watch to the end (8 minutes), it shows an interesting reactive way to manage state.

However, I haven't seen any large application use this pattern, though that is more likely due to my inexperience in this area than anything else. Alternatively I have used Redux on some projects recently, and it drastically improves the testability and clarity of the data flow in the application.

**Comment by dignifiedquire** [comment]
@aeschylus thanks for the mention. I've been looking into rxjs and the different ways how to use it in combination with React for some time now. The reason why I did not go the CycleJS route is that it would require a full rewrite of the webui + there are many more people at the moment using and understanding React and I'd love to have some help around here and keep it as accessible as reasonable. 

BUT I just discovered this: https://gist.github.com/tomkis1/8b3573ca9483d60c8b34 redux-saga with rxjs observables, so I'm going to try and use this in my PR. 

Also you can see the stack I'm using currently in #229 which is redux + redux-saga right now.

**Comment by dignifiedquire** [comment]
Also referencing https://github.com/yelouafi/redux-saga/issues/105 which I need to read, and everyone else interested in sagas and observables should probably as well.

**Comment by mcmunder** [comment]
Not sure what the status of this issue is (obviously you went with Sagas...). I use [redux-observable](https://redux-observable.js.org/) in my current project and I like it a lot (and much more than Sagas) so far. Just wanted to advertise it here...

❤️ IPFS and would like to contribute!

**Comment by dignifiedquire** [comment]
Thank you @mcmunder I have been using [redux-logic](https://github.com/jeffbski/redux-logic) in another project very happily since then which rx under the hood but provides a very nice way of interaction without actually having to use rx directly.

**Comment by mcmunder** [comment]
Great, thanks! Didn't know about `redux-logic` so I will definitely give it a closer look!

**Comment by hacdias** [comment]
The coming release (2.0.0) uses redux!
