### ISSUE TITLE
"About IPFS" should link to the IPFS-hosted version of the website

### ISSUE THREAD

**Issue by chungy** [ipfs-shipyard/ipfs-webui#315]
Rather than linking to http://ipfs.io/, it seems more appropriate to link instead to http://localhost:8080/ipns/ipfs.io (or whatever the local gateway address is). It would promote the usage of IPFS within the system itself.

**Comment by olizilla** [comment]
https://ipfs.io has a [dnslink](https://docs.ipfs.io/guides/concepts/dnslink/) record that points to the latest CID for the site. 

```console
$ jsipfs dns ipfs.io
/ipns/website.ipfs.io
```

If you have [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) installed it will detect it and redirect the request to you local IPFS gateway and load the site over IPFS rather than http, which is rad! Using http links with dnslink for the domain is a good way of ensuring that both IPFS and non IPFS users can use them. 

In the case of the Web UI it would be cool to use http://localhost:8080/ipns/ipfs.io but then it's not a URL you can easily share with friends who aren't already set up with a local IPFS daemon.
