### ISSUE TITLE
Add detection and warning message for CORS issues

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/ipfs-webui#578]
I think one of the biggest problems people run into with the webui is CORS issues. These should be pretty easy to detect from javascript right? Just make an api query and see if we get a 403? How about we show a notice to the user if their cors things arent properly configured and point them to an issue or guide on fixing it

**Comment by Kubuxu** [comment]
Not really, CORS is enforced on browser XHR engine level, with quite cryptic errors IIRC.

**Comment by VictorBjelkholm** [comment]
We can't see specifically see it's a CORS error but we can see if there is errors, print those out and link to a troubleshooting guide.

**Comment by olizilla** [comment]
CORS errors are deliberately hidden from JS 

> CORS failures result in errors, but for security reasons, specifics about what went wrong are not available to JavaScript code. All the code knows is that an error occurred. The only way to determine what specifically went wrong is to look at the browser's console for details.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

We could try requesting the empty dir CID from a gateway running on the default port http://127.0.0.1:8080/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

That way we can infer if you have a daemon running or not, but we don't get to know if an API request failure is because you have configured your api to run on a different port, or if you need to configure CORS headers for the domain that is serving the version of web ui making the request.
