### ISSUE TITLE
New name! 

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-webui#612]
Following the lead of https://github.com/ipfs-shipyard/ipfs-station/issues/561, we also want to find a better name for the IPFS WebUI.

Please submit your proposals by creating a _separate comment per proposal_ and give votes with 👍 👎 on that comment.

**Comment by diasdavid** [comment]
`IPFS Control Room`

**Comment by diasdavid** [comment]
`IPFS Admin Panel`

**Comment by diasdavid** [comment]
`IPFS Admin Console`

**Comment by diasdavid** [comment]
`IPFS Dashboard`

**Comment by lgierth** [comment]
`IPFS Admin` (makes even more sense if we also name :5001 the "admin port", which would be a good thing)

**Comment by lgierth** [comment]
`IPFS Control` (makes even more sense if we also name :5001 the "control port", which would be a good thing)

**Comment by lgierth** [comment]
Voted 👎 on IPFS Dashboard because it sounds a bit too harmless to me. This is a webapp that gives you full privileges over the ipfs node, and not just by means of its functionality, but simply by being on the same port as the API (:5001). In other server-ish projects a dashboard is often something that's okay to put on the internet. (With some projects, you're even encouraged to.)

It would be good to pick a name that conveys some degree of delicacy.

**Comment by lgierth** [comment]
(I'd also like to propose to make the majority vote here non-binding. I wouldn't care if it were only a matter of finding a name that's nice, but it's also a matter of preventing security missteps by users before they even arise.)

**Comment by bentoncbainbridge** [comment]
IPFS Space Center

**Comment by VictorBjelkholm** [comment]
`ipfs-webui`

**Comment by diasdavid** [comment]
I hear your points @lgierth, I believe that something that might be causing the confusion is that we have nice things for users to interact with (DAG explorer, files, connections) mixed with Admin features (config). I'm starting to feel that we should have a Dashboard & an Admin Panel

**Comment by lidel** [comment]
Ok, so it seems we don't have anything better than the current name (WebUI). Removing voting from title.
Let's keep this issue open to invite new ideas that address concerns raised here.

**Comment by Admin-DataRoads** [comment]
Voted :+1: on IPFS Control because it's concise and conveys similar gravitas to admin level config. I also agree with @diasdavid though, that the separation between read-only access features and configuration-write features are a very important distinction -- important enough to separate the tools capable of doing each. Maybe `IPFS Control` (admin config-write feature superset) and `IPFS Node Explorer` (read-only local-node config subset)?

In any case, if an [IPFS HTTPS-WebDAV gateway](https://github.com/ipfs/go-ipfs-gateway/issues/9) is ever completed, then I may consider that closer to a general IPFS WebUI than this project per se. That gateway interface also has the advantage of existing POSIX translation and remote file system support in every OS, which could be considered non-browser forms of WebUI.

**Comment by adotka** [comment]
IPFS Web

**Comment by Gozala** [comment]
`IPFS Control Panel`

**Comment by fsdiogo** [comment]
Closing as this is not relevant for the near future.

Ref: https://github.com/ipfs/ipfs-gui/issues/5#issuecomment-467038783
