### ISSUE TITLE
Improve reporting of files upload error

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-webui#821]
I have `window.ipfs` talking to an external js-ipfs daemon v0.32.

When I add a folder the button eventually changes to 100% and then I get a "Normal service is resumed" message. Files do not appear in the explorer.

**Comment by olizilla** [comment]
I've reduced all errors down to "ipfs has gone", which is a bit too reductive. We need a custom notification for when file upload goes wrong. @hacdias put all the plumbing in place, but I was rushing, and disabled it. It needs to come back, but we can use the notify bundle to figure out what to show and when.

**Comment by olizilla** [comment]
There is the bigger issue that we have a bug with large or multiple file uploads, but that is a known issue. Web UI needs to do a good job of warning the user when problems occur.

**Comment by olizilla** [comment]
File upload issue is documented here https://github.com/ipfs/go-ipfs/issues/5168

**Comment by olizilla** [comment]
@fsdiogo could you take a look at the error reporting in Web UI pls. The notify bundle needs to be reworked so that it only tells the user that the connection to IPFS has failed when the bandwidth stats request fails. (that's not totally ideal, I know, but we poll it every 3s and we're using that to figure out when the daemon goes away in the connection bundle, so it's consistent at least) 

Right now, we're taking all `FETCH-*-FAILED` redux actions to mean that connection was lost, but this isn't helpful as it smothers more specific errors. We should try and show things like "Failed to add file to IPFS" as there own specific notifications. Maybe start with that, but don't try and deal with all the error conditions in 1 PR, as it's a big job.
