### ISSUE TITLE
feature: realtime chat widget

### ISSUE THREAD

**Issue by cwaring** [ipfs-shipyard/ipfs-webui#984]
Related to discussions in #979. I'd like to propose the addition of a realtime support widget such as Intercom as a way to capture feedback from users.

Context: currently the web-ui is making many assumptions about what users want to achieve with the app and how they should go about doing it. By exposing a quick channel to Real Human Support™ I believe we could learn some valuable insights on what people outside of our team find confusing or difficult to achieve, which we could feed back into our product cycles.

This could work alongside the on-boarding tour or as a quicker way to gather direct feedback. I would suggest we trial this with a subset of the audience if possible instead of it being on by default all the time.

Let's use this issue to capture examples and implementation ideas.  I'm keen to hear your thoughts 💭

**Comment by olizilla** [comment]
I like the idea of being available to help users, and using it as a mechanism to get first hand evidence of what is and isn't working. There are some questions though:

- How do we staff it? Between family and work commitments I can't volunteer for it.
- Could we achieve much of what we want from this through more structured and regular user testing? and a help system.
- This isn't a core feature of webui so we'd be looking at dropping in a system provided by a third party rather than building it ourselves. Do you have any recommendations?
  - Do any "help chat as a service" systems exist with strong user privacy policys? Re: #980

**Comment by cwaring** [comment]
Stale issue, closing for now.
